---
- name: test demo
  hosts: qotd_bastion
  tasks:
    - name: TEST -           🚀 Get Nodes
      shell: |
        kubectl get nodes 
      register: nodes
      ignore_errors: yes


    - name: DEBUG -                 🟢 NODES
      debug:
        var: nodes.stdout_lines
